### ISSUE TITLE
MINT::PTEB 重定义

### ISSUE THREAD

**Issue by nblog** [Chuyu-Team/MINT#3]
MINT.h(9278,9): error C2371: “MINT::PTEB”: 重定义；不同的基类型
MINT.h(4048): message : 参见“MINT::PTEB”的声明

**Comment by nblog** [comment]
[typedef struct _TEB](https://github.com/Chuyu-Team/MINT/blob/master/MINT.h#L9111)
修改为: "struct _TEB"

[} TEB, *PTEB;](https://github.com/Chuyu-Team/MINT/blob/master/MINT.h#L9278)
修正为: "};"

[typedef struct _TEB *PTEB;](https://github.com/Chuyu-Team/MINT/blob/master/MINT.h#L4048)
修正为: "typedef struct _TEB TEB, *PTEB;"

**Comment by MouriNaruto** [comment]
收到，我最近会修复的

**Comment by MouriNaruto** [comment]
已经在 https://github.com/Chuyu-Team/MINT/commit/bddab257851b74c72979f42996febedc02137edf 中修复，非常感谢。
