### ISSUE TITLE
I hope to add support for MinGW GCC and TDM GCC

### ISSUE THREAD

**Issue by xinyugit** [Chuyu-Team/MINT#4]
I hope to add support for MinGW GCC and TDM GCC

**Comment by MouriNaruto** [comment]
I don't think it's wise for developers to use non-MSVC compiler to develop Windows applications.

Because Windows SDK and Windows WDK rely on MSVC compiler.

Kenji Mouri

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xinyugit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
